version: 2
jobs:
  build:
    working_directory: ~/ledgers.js
    docker:
      - image: circleci/node:chakracore-10.13.0-browsers
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm run all
          background: true
      - run:
          name: test
          command: npm run test-report
      - store_test_results:
          path: ./test-report
      - store_artifacts:
          path: ./test-report